product:
  max_length_name: 100
  max_residual: 5000
rating_min: 1
rating_max: 5
content_max: 250
length:
  max_length_email: 150
  min_length_username: 6
  max_length_username: 50
  min_length_password: 6
currency_regex: !ruby/regexp /\A[+-]?(\d+\.\d+)?\Z/
size:
  page_record_medium: 6
admin:
  order_status:
    pending: 0
    accept: 1
    cancel: 2
    reject_: 3
  order_option:
    oldest: "0"
    newest: "1"
    status: "2"
  product_option:
    oldest: "1"
    newest: "2"
    price: "3"
    price_desc: "4"
    all: "5"
  product_sorts: [["Oldest", 1], ["Newest", 2], ["Price", 3], ["Desc Price", 4], ["All", 5]]
  product:
    image:
      format: ["image/png", "image/jpg", "image/jpeg"]
      less_than: 5
      width: 70
      height: 70
      width_200: 200
      height_200: 200
